<?php

namespace Bolt\Core\Serializer;

use Composer\Autoload\ClassLoader;

use Layla\Cody\Blueprints\Package;
use Layla\Cody\Blueprints\Resource;
use Layla\Cody\Compilers\Php\Core\NamespaceCompiler;

class CodyLaravelSerializer
{
    public function __construct($app)
    {
        $this->app = $app;
    }

    public function serialize()
    {
        $app = $this->app;

        foreach($app['contenttypes'] as $contentType) {
            $key = $contentType->getKey();

            $generatedModel = $this->getGeneratedModel($contentType);
            $model = $this->getModel($contentType);
            $repository = $this->getRepository($contentType);

            foreach(array($generatedModel, $model, $repository) as $resource) {
                foreach($resource->getCompilerObjects() as $compiler) {
                    $path = $app['paths.root'].'vendor/';
                    $destination = $path . $compiler->getDestination();
                    $path = dirname($destination);

                    if( ! is_dir($path)) {
                        `mkdir -p $path`;
                    }

                    if( ! file_exists($destination) || $resource->get('force', false))
                    {
                        file_put_contents($destination, $compiler->compile());
                    }
                }
            }

            $package = $this->getPackage();
            $vendor = $package->getVendor();
            $lowerVendor = strtolower($vendor);
            $name = $package->getName();
            $lowerName = strtolower($name);

            $app['autoloader']->add($vendor.'\\'.$name, $app['paths.root'].'vendor/'.$lowerVendor.'/'.$lowerName.'/src');

            $this->registerModel($key, $model);
            $this->registerRepository($key, $repository);
        }
    }

    protected function getPackage()
    {
        $config = $this->app['config'];

        $vendor = $config->get('app/package/vendor', 'MyApp');
        $name = $config->get('app/package/name', 'Domain');

        return new Package($vendor, $name);
    }

    protected function getGeneratedModel($contentType)
    {
        $package = $this->getPackage();

        $type = 'model';

        $name = $this->getGeneratedModelName($contentType);

        $configuration = array(
            'force' => true,
            'comment' => 'THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT!!!!!!!',
            'base' => 'Bolt.Core.Content.Eloquent.Model',
            'table' => $contentType->getKey(),
            'columns' => $this->getModelColumns($contentType)
        );

        $compilers = array(
            'php-laravel'
        );

        return new Resource($package, $type, $name, $configuration, $compilers);
    }

    protected function getGeneratedModelName($contentType)
    {
        $package = $this->getPackage();

        $parts = array(
            $package->getVendor(),
            $package->getName(),
            'Models',
            'Generated',
            'Generated'.ucfirst($contentType->getSingularSlug())
        );

        return implode('.', $parts);
    }

    protected function getModel($contentType)
    {
        $package = $this->getPackage();

        $type = 'class';

        $name = $this->getModelName($contentType);

        $configuration = array(
            'base' => $this->getGeneratedModelName($contentType)
        );

        $compilers = array(
            'php-core'
        );

        return new Resource($package, $type, $name, $configuration, $compilers);
    }

    protected function getModelName($contentType)
    {
        $package = $this->getPackage();

        $parts = array(
            $package->getVendor(),
            $package->getName(),
            'Models',
            ucfirst($contentType->getSingularSlug())
        );

        return implode('.', $parts);
    }

    protected function getModelColumns($contentType)
    {
        $columns = array();

        foreach ($contentType->getFields() as $field) {
            $config = $field->getType()->getMigratorConfig();

            $columns[$field->getKey()] = array_merge(array(
                'type' => $config['type']
            ), $config['options']);
        }

        return $columns;
    }

    protected function getRepository($contentType)
    {
        $package = $this->getPackage();

        $type = 'class';

        $name = $this->getRepositoryName($contentType);

        $configuration = array(
            'force' => true,
            'comment' => 'THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT!!!!!!!',
            'base' => 'Bolt.Core.Content.Eloquent.EloquentRepository',
        );

        $compilers = array(
            'php-core'
        );

        return new Resource($package, $type, $name, $configuration, $compilers);
    }

    protected function getRepositoryName($contentType)
    {
        $package = $this->getPackage();

        $parts = array(
            $package->getVendor(),
            $package->getName(),
            'Repositories',
            'Generated',
            ucfirst($contentType->getSingularSlug()).'Repository'
        );

        return implode('.', $parts);
    }

    protected function registerModel($key, $model)
    {
        $app = $this->app;
        $namespaceCompiler = new NamespaceCompiler($model->getName());
        $className = $namespaceCompiler->getName();
        $app['model.'.$key] = $app->share(function($app) use ($className) {
            return new $className;
        });
    }

    protected function registerRepository($key, $repository)
    {
        $app = $this->app;
        $namespaceCompiler = new NamespaceCompiler($repository->getName());
        $className = $namespaceCompiler->getName();
        $app['repository.'.$key] = $app->share(function($app) use ($className, $key) {
            return new $className($app['model.'.$key], $app['contenttypes']->get($key));
        });
    }

}
